# This file is used to define the runners for the Marqo project.
# Due to the way Runs-on product works, file for opensource repository is read from mainline branch.
# Therefore to make any changes to runners configuration you need to merge them to mainline branch.
# The workaround is to override the runners in the workflow file itself.
# Like that: runs-on: "runs-on=${{ github.run_id }}/family=g4dn.2xlarge/ami=${{ vars.MARQO_CUDA_TESTS_INSTANCE_AMI }}"
images:
  marqo-cpu-image:
    ami: "ami-0b8bc108d37bb85f3"

  marqo-gpu-image:
    ami: "ami-05552d0fb705d800e"

  marqo-cpu-arm-image:
    ami: "ami-055eacc4029e4a094"

runners:
  marqo-cpu-runner:
    family: ["m6i.xlarge"]
    tags:
      - PoloRole: "testing"
    image: marqo-cpu-image

  marqo-gpu-runner:
    family: ["g4dn.2xlarge"]
    tags:
      - PoloRole: "testing"
    image: marqo-gpu-image

  marqo-cpu-multinode-runner:
    family: ["m6i.2xlarge"]
    tags:
      - PoloRole: "testing"
    image: marqo-cpu-image

  marqo-cpu-arm-runner:
    family: ["r7g.large"]
    tags:
      - PoloRole: "testing"
    image: marqo-cpu-arm-image
    spot: false

  marqo-perf-tests-runner:
    family: ["t3.xlarge"]
    tags:
      - PoloRole: "testing"
    image: marqo-cpu-image