#A Docker Compose file to set up a Marqo inference environment with Triton Inference Server,
#Marqo Model Management Container (MMC), and Marqo Inference Orchestrator Container(MIOC).
#
#This will expose the vectorise endpoint in MIOC on port 8884. Integration tests can be run against this endpoint.

name: marqo-inference

services:
  triton-gpu:
    image: nvcr.io/nvidia/tritonserver:25.08-py3
    command:
      [
        "tritonserver",
        "--model-repository=/models",
        "--log-verbose=1",
        "--model-control-mode=explicit"
      ]
    volumes:
      - modelrepo:/models          # <== shared
    ports:
      - "8000:8000"                # HTTP
      - "8001:8001"                # gRPC
      - "8002:8002"                # Metrics
    networks:
      mmc-net:
        aliases: [triton-cpu]
    profiles: [gpu]
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  triton-cpu:
    image: nvcr.io/nvidia/tritonserver:25.08-py3
    command:
      [
        "tritonserver",
        "--model-repository=/models",
        "--log-verbose=1",
        "--model-control-mode=explicit"
      ]
    volumes:
      - modelrepo:/models          # <== shared
    ports:
      - "8000:8000"                # HTTP
      - "8001:8001"                # gRPC
      - "8002:8002"                # Metrics
    networks: [ mmc-net ]
    profiles: [cpu]
    restart: unless-stopped

  mmc:
    image: marqo-model-management-container:latest
    build: ./components/model_management
    stdin_open: true
    tty: true
    environment:
      MARQO_LOG_LEVEL: "INFO"
      MARQO_MODELS_TO_PRELOAD: "[]"
      TRITON_URL: http://triton:8000
      MODEL_BASE_DIR: /models
    volumes:
      - modelrepo:/models
    ports:
      - "8883:8883"
    networks: [mmc-net]
    restart: unless-stopped

  mioc:
    image: marqo-inference-orchestrator-container:latest
    build: ./components/inference_orchestrator
    stdin_open: true
    tty: true
    environment:
      LOG_LEVEL: "INFO"
      MARQO_TRITON_URL: http://triton:8001
      MARQO_MODEL_MANAGEMENT_CONTAINER_URL: http://mmc:8883
    ports:
      - "8884:8884"
    networks: [mmc-net]
    restart: unless-stopped

volumes:
  modelrepo:

networks:
  mmc-net: