# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

apiVersion: v1
kind: Service
metadata:
  name: vespa-internal
  labels:
    name: vespa-internal
spec:
  selector:
    name: vespa-internal
  clusterIP: None