# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

apiVersion: v1
kind: Service
metadata:
  name: vespa-query
  labels:
    app: vespa
spec:
  # Set LoadBalancer for an endpoint reachable from the internet
  type: LoadBalancer
  selector:
    app: vespa-query-container
  ports:
  - name: api
    port: 8080
    targetPort: 8080
