# An example docker-compose file to run Triton Inference Server with Marqo Model Management Container (MMC).
# Make sure to replace the placeholder for the model repository path before running.

services:
  triton:
    image: nvcr.io/nvidia/tritonserver:25.08-py3
    command:
      [
        "tritonserver",
        "--model-repository=/models",
        "--log-verbose=1",
        "--model-control-mode=explicit"
      ]
    volumes:
      - modelrepo:/models          # <== shared
    ports:
      - "8000:8000"                # HTTP
      - "8001:8001"                # gRPC
      - "8002:8002"                # Metrics
    networks: [mmc-net]
    restart: unless-stopped

  mmc:
    image: marqo-model-management-container:test
    build: .
    stdin_open: true
    tty: true
    environment:
      LOG_LEVEL: "INFO"
      MARQO_MODELS_TO_PRELOAD: "[]"
      TRITON_URL: http://triton:8000
      MODEL_BASE_DIR: /models
    volumes:
      - modelrepo:/models
      # - ~/.aws/credentials:/root/.aws/credentials
    ports:
      - "8883:8883"
    networks: [mmc-net]
    restart: unless-stopped

volumes:
  modelrepo:
     driver: local
     driver_opts:
       type: none
       o: bind
       # device: <> <== path to local model repository

networks:
  mmc-net:

