worker_processes 4;

events {
    worker_connections 512;
}

http {
    client_max_body_size 100M;
    proxy_buffers 8 1M;
    proxy_buffer_size 2M;
    client_body_timeout 300;
    client_header_timeout 300;
    keepalive_timeout 75;
    limit_conn_zone $server_name zone=global:1m;

    upstream marqo_backend {
        server 127.0.0.1:8882;  # Marqo app listens here
    }

    server {
        listen 7000;

        location / {
            limit_conn global 40;
            limit_conn_status 429;

            proxy_pass http://marqo_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            error_page 429 /429.json;
            proxy_read_timeout 300;
        }

        location /429.json {
            return 429 '{"message": "Throttled because maximum number of requests has been exceeded.", "code": "too_many_requests"}';
        }
        location /nginx_status {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }

    }
}
