model_config = {
    "all-MiniLM-L6-v2-text-encoder": {
        "name": "all-MiniLM-L6-v2-text-encoder",
        "platform": "onnxruntime_onnx",
        "backend": "onnxruntime",
        "runtime": "",
        "version_policy": {"latest": {"num_versions": 1}},
        "max_batch_size": 16,
        "input": [
            {
                "name": "input_ids",
                "data_type": "TYPE_INT64",
                "format": "FORMAT_NONE",
                "dims": [-1],
                "is_shape_tensor": False,
                "allow_ragged_batch": False,
                "optional": False,
                "is_non_linear_format_io": False,
            },
            {
                "name": "attention_mask",
                "data_type": "TYPE_INT64",
                "format": "FORMAT_NONE",
                "dims": [-1],
                "is_shape_tensor": False,
                "allow_ragged_batch": False,
                "optional": False,
                "is_non_linear_format_io": False,
            },
            {
                "name": "token_type_ids",
                "data_type": "TYPE_INT64",
                "format": "FORMAT_NONE",
                "dims": [-1],
                "is_shape_tensor": False,
                "allow_ragged_batch": False,
                "optional": False,
                "is_non_linear_format_io": False,
            },
        ],
        "output": [
            {
                "name": "last_hidden_state",
                "data_type": "TYPE_FP32",
                "dims": [-1, 384],
                "label_filename": "",
                "is_shape_tensor": False,
                "is_non_linear_format_io": False,
            }
        ],
        "batch_input": [],
        "batch_output": [],
        "optimization": {
            "priority": "PRIORITY_DEFAULT",
            "input_pinned_memory": {"enable": True},
            "output_pinned_memory": {"enable": True},
            "gather_kernel_buffer_threshold": 0,
            "eager_batching": False,
        },
        "dynamic_batching": {
            "preferred_batch_size": [16],
            "max_queue_delay_microseconds": 0,
            "preserve_ordering": False,
            "priority_levels": 0,
            "default_priority_level": 0,
            "priority_queue_policy": {},
        },
        "instance_group": [
            {
                "name": "all-MiniLM-L6-v2-text-encoder",
                "kind": "KIND_CPU",
                "count": 2,
                "gpus": [],
                "secondary_devices": [],
                "profile": [],
                "passive": False,
                "host_policy": "",
            }
        ],
        "default_model_filename": "model.onnx",
        "cc_model_filenames": {},
        "metric_tags": {},
        "parameters": {},
        "model_warmup": [],
    },
    "marqo-fashionSigLIP-image-encoder": {
        "name": "marqo-fashionSigLIP-image-encoder",
        "platform": "onnxruntime_onnx",
        "backend": "onnxruntime",
        "runtime": "",
        "version_policy": {"latest": {"num_versions": 1}},
        "max_batch_size": 8,
        "input": [
            {
                "name": "input",
                "data_type": "TYPE_FP32",
                "format": "FORMAT_NONE",
                "dims": [3, 224, 224],
                "is_shape_tensor": False,
                "allow_ragged_batch": False,
                "optional": False,
                "is_non_linear_format_io": False,
            }
        ],
        "output": [
            {
                "name": "output",
                "data_type": "TYPE_FP32",
                "dims": [768],
                "label_filename": "",
                "is_shape_tensor": False,
                "is_non_linear_format_io": False,
            }
        ],
        "batch_input": [],
        "batch_output": [],
        "optimization": {
            "priority": "PRIORITY_DEFAULT",
            "input_pinned_memory": {"enable": True},
            "output_pinned_memory": {"enable": True},
            "gather_kernel_buffer_threshold": 0,
            "eager_batching": False,
        },
        "dynamic_batching": {
            "preferred_batch_size": [8],
            "max_queue_delay_microseconds": 0,
            "preserve_ordering": False,
            "priority_levels": 0,
            "default_priority_level": 0,
            "priority_queue_policy": {},
        },
        "instance_group": [
            {
                "name": "marqo-fashionSigLIP-image-encoder",
                "kind": "KIND_CPU",
                "count": 2,
                "gpus": [],
                "secondary_devices": [],
                "profile": [],
                "passive": False,
                "host_policy": "",
            }
        ],
        "default_model_filename": "model.onnx",
        "cc_model_filenames": {},
        "metric_tags": {},
        "parameters": {},
        "model_warmup": [],
    },
}
