# Orchestrator workflow
name: Marqo Compatibility Tests Orchestrator

on:
  push: #TODO: Decide if this workflow should run on push. Doesn't make sense to run on push, since we'll need to somehow have context of what is the to_version and then derive from_versions from those.
    branches:
      - mainline
    paths-ignore:
      - '**.md'
  workflow_dispatch:
    inputs:
      to_version:
        description: 'Target Marqo version'
        required: true
      to_image:
        description: 'Target Marqo image (optional)'
        required: false
      max_versions_to_test:
        description: 'Max versions to test'
        required: false

# Setting MAX_VERSIONS_TO_TEST, this can be a configurable value or if no input is provided, it can be a default value.
env:
  MAX_VERSIONS_TO_TEST: ${{ github.event.inputs.max_versions_to_test || 3 }}

jobs:
  invoke-build-push-img-github-workflow:
    # Responsible for invoking build_push_img.yml GitHub actions workflow in the same repo
    # that builds a marqo commit using the latest commit and uploads it to a private ECR Registry.
    # More in /marqo/.github/workflows/build_push_img.yml
    name: Invoke build_push_img.yml github actions workflow
    runs-on: ubuntu-latest
    environment: marqo-test-suite
    steps:
      - name: Checkout marqo repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and push marqo image to ECR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          to_version: ${{ github.event.inputs.to_version }}
        run: |
          # Build and push image to ECR
          echo "Building and pushing marqo image to ECR"
          echo "printing the commit sha" + ${{ github.sha }}
          workflow_data="{\"ref\": \"mainline\",\"inputs\": {\"marqo_ref\": \"${{ github.sha }}\", \"push_to\": \"ECR\",\"image_repo\": \"marqo-compatibility-tests\",\"image_tag\":\"${{ github.sha }}\"}}"
          echo "printing the workflow_data" + $workflow_data
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/marqo-ai/marqo/actions/workflows/build_push_img.yml/dispatches \
            -d "$workflow_data"

  poll-for-image-existence:
    # Responsible for polling the ECR registry for the image to be available
    # More in /marqo/.github/workflows/build_push_img.yml
    name: Poll for image existence
    runs-on: ubuntu-latest
    environment: marqo-test-suite
    needs: invoke-build-push-img-github-workflow
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ECR_PUSHER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_PUSHER_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Poll for image existence
        run: |
          echo "Polling for image existence"
          MAX_RETRIES=20  # Adjust retries as needed
          SLEEP_TIME=60   # Adjust polling interval as needed
          for ((i=1; i<=MAX_RETRIES; i++)); do
            if aws ecr describe-images --repository-name marqo-compatibility-tests --image-ids imageTag=${{ github.sha }}; then
              echo "Image found in ECR"
              exit 0
            else
              echo "Image not found in ECR, retrying in $SLEEP_TIME seconds..."
              sleep $SLEEP_TIME
            fi
          done
          echo "Image not found after $MAX_RETRIES attempts. Exiting."
          exit 1

  orchestrate:
    name: Orchestrate backwards compatibility test execution
    runs-on: ubuntu-latest
    needs: poll-for-image-existence

    environment: marqo-test-suite
    steps:
      - name: Checkout marqo repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          cache: "pip"

      - name: Install semver
        run: |
          pip install semver

      - name: Generate version list #this code block just generates the from versions and stores it in a versions variable as a list
        id: versions
        run: |
          # Run the Python script and capture its output
          VERSION_LIST=$(python tests/backwards_compatibility_tests/generate_versions.py ${{ github.event.inputs.to_version }} ${{ env.MAX_VERSIONS_TO_TEST }})
          echo "::set-output name=list::$VERSION_LIST" # setting the output variable

      - name: display versions
        run: | 
          echo "Versions to test: ${{ steps.versions.outputs.list }}"

      - name: Trigger execution workflows #this code block is then actually responsible for running the the execution yaml file with from_version / to_version combinations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #check if this is required
        run: |
          for from_version in ${{ steps.versions.outputs.list }}
          do
            workflow_data="{\"ref\":\"${{ github.ref }}\",\"inputs\":{\"from_version\":\"$from_version\",\"to_version\":\"${{ github.event.inputs.to_version }}\",\"to_version_tag\":\"${{ github.sha }}\""
            
            if [ -n "${{ github.event.inputs.to_image }}" ]; then
              workflow_data="$workflow_data,\"to_image\":\"${{ github.event.inputs.to_image }}\""
            fi
            workflow_data="$workflow_data}}"
            echo "printing workflow_data + " $workflow_data
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/marqo-ai/marqo/actions/workflows/backwards_compatibility_marqo_execution.yml/dispatches \
              -d "$workflow_data"
          done