# Orchestrator workflow
name: Marqo Compatibility Tests Orchestrator

on:
  push:
    branches:
      - mainline
    paths-ignore:
      - '**.md'
  workflow_dispatch:
    inputs:
      to_version:
        description: 'Target Marqo version'
        required: true
      to_image:
        description: 'Target Marqo image (optional)'
        required: false
      max_versions_to_test:
        description: 'Max versions to test'
        required: false

# Setting MAX_VERSIONS_TO_TEST, this can be a configurable value or if no input is provided, it can be a default value.
env:
  MAX_VERSIONS_TO_TEST: ${{ github.event.inputs.max_versions_to_test || 3 }}

jobs:
  invoke-build-push-img-github-workflow:
    # Responsible for invoking build_push_img.yml GitHub actions workflow in the same repo
    # that builds a marqo commit using the latest commit and uploads it to a private ECR Registry.
    # More in /marqo/.github/workflows/build_push_img.yml
    name: Invoke build_push_img.yml github actions workflow
    runs-on: ubuntu-latest
    environment: marqo-test-suite
    steps:
      - name: Checkout marqo repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # step to check for image existence - it uses aws cli to check if the image exists in the ECR registry "marqo-compatibility-tests"
      - name: check for image existence
        id: check-image
        run: |
          echo "Checking for image existence"
          if aws ecr describe-images --repository-name marqo-compatibility-tests --image-ids imageTag=${{ github.sha }}; then
            echo "::set-output name=image_exists::true"
          else
            echo "::set-output name=image_exists::false"
          fi

      # Step to build and push marqo image to ECR, only executes if the image does not exist signified by image_exists == false.
      - name: Build and Push Image
        id: build-and-push-image
        if: steps.check-image.outputs.image_exists == 'false'
        uses: ./.github/workflows/build_push_img.yml
        with:
          marqo_ref: "${{ github.sha }}"
          push_to: "ECR"
          image_repo: "marqo-compatibility-tests"
          image_tag: "${{ github.sha }}"

  orchestrate:
    # Job to orchestrate backwards compatibility test execution
    name: Orchestrate backwards compatibility test execution
    runs-on: ubuntu-latest
    needs: invoke-build-push-img-github-workflow

    environment: marqo-test-suite
    steps:
      # Step to check out the Marqo repository
      - name: Checkout marqo repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step to set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: "pip"

      # Step to install the semver package
      - name: Install semver
        run: |
          pip install semver


      # Step to determine the target version
      - name: Determine to_version
        if: $${{ github.event_name != 'workflow_dispatch' && !github.event.inputs.to_version }} # If this condition is met it signifies
        # that the run was triggered due to mainline push and was not manual. In that case we need to calculate to_version below. This is skipped otherwise.
        id: get-version
        run: |
          VERSION=$(python tests/backwards_compatibility_tests/scripts/determine_to_version.py ${{ github.sha }})
          echo "::set-output name=to_version::$VERSION"

      # Step to generate the list of versions to test
      - name: Generate version list #this code block just generates the from_version list and stores it in a versions variable as a list
        id: versions
        run: |
          # Run the Python script and capture its output
          VERSION_LIST=$(python tests/backwards_compatibility_tests/scripts/generate_versions.py ${{ steps.get-version.outputs.to_version }} ${{ env.MAX_VERSIONS_TO_TEST }})
          echo "::set-output name=list::$VERSION_LIST" 

      # Step to display the versions to test
      - name: display versions
        run: | 
          echo "Versions to test: ${{ steps.versions.outputs.list }} against to_version: ${{ steps.get-version.outputs.to_version }}"

      # Step to trigger execution workflows for each version combination
  run-execution-workflow:
    name: Backwards Compatibility Tests
    runs-on: ubuntu-latest
    needs: orchestrate
    strategy:
      matrix:
        from_version: ${{ fromJson(needs.orchestrate.outputs.list) }}
    uses: ./.github/workflows/backwards_compatibility_marqo_execution.yml
    with:
      from_version: ${{ matrix.from_version }}
      to_version: ${{ needs.orchestrate.outputs.to_version }}
      to_version_tag: ${{ github.sha }}
      to_image: ${{ github.event.inputs.to_image || '' }}
