# Execution workflow
name: Marqo Test Compatibility Execution

on:
  workflow_dispatch:
    inputs:
      from_version:
        description: 'Source Marqo version'
        required: true
      to_version:
        description: 'Target Marqo version'
        required: true
      to_version_tag:
        description: 'Target Marqo version tag'
        required: true
      from_image:
        description: 'Source Marqo image (optional)'
        required: false
      to_image:
        description: 'Target Marqo image (optional)'
        required: false

jobs:
  Start-Runner:
    permissions: write-all
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MARQO_WORKFLOW_TESTS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MARQO_WORKFLOW_TESTS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ${{ secrets.MARQO_CPU_AMD64_TESTS_INSTANCE_AMI }}
          ec2-instance-type: m6i.xlarge
          subnet-id: ${{ secrets.MARQO_WORKFLOW_TESTS_SUBNET_ID }}
          security-group-id: ${{ secrets.MARQO_WORKFLOW_TESTS_SECURITY_GROUP_ID }}
          aws-resource-tags: > # optional, requires additional permissions
            [
              {"Key": "Name", "Value": "marqo-compatibility-test-runner-${{ github.run_id }}"},
              {"Key": "GitHubRepo", "Value": "${{ github.repository }}"},
              {"Key": "WorkflowName", "Value": "${{ github.workflow }}"},
              {"Key": "WorkflowRunId", "Value": "${{ github.run_id }}"},
              {"Key": "WorlflowURL", "Value": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"},
              {"Key": "PoloRole", "Value": "testing"}
            ]
            
  backwards_compatibility:
    runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner
    needs: Start-Runner
    steps:
      - name: checkout marqo repo
        uses: actions/checkout@v3
        with:
          repository: marqo-ai/marqo
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install pip-tools
        run: |
          python -m pip install pip-tools

      - name: Install Dependencies
        run: |
          pip install -r tests/backwards_compatibility_tests/requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ECR_PUSHER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_PUSHER_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Login to Amazon ECR registry
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 424082663841.dkr.ecr.us-east-1.amazonaws.com

      - name: Run backwards_compatibility test
        run: |
          cmd="python tests/backwards_compatibility_tests/compatibility_test_runner.py \
            --mode=backwards_compatibility \
            --from_version ${{ github.event.inputs.from_version }} \
            --to_version ${{ github.event.inputs.to_version }} \
            --to_version_tag ${{ github.event.inputs.to_version_tag }}"
          if [ -n "${{ github.event.inputs.from_image }}" ]; then
            cmd="$cmd --from_image ${{ github.event.inputs.from_image }}"
          fi
          if [ -n "${{ github.event.inputs.to_image }}" ]; then
            cmd="$cmd --to_image ${{ github.event.inputs.to_image }}"
          fi
          eval $cmd

  Stop-Runner:
    name: Stop self-hosted EC2 runner
    needs:
      - Start-Runner # required to get output from the start-runner job
      - backwards_compatibility # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MARQO_WORKFLOW_TESTS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MARQO_WORKFLOW_TESTS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
