name: Dispatcher
on:
  release:
    types: [released]

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['marqo-ai/models-list-script']
    steps:
      - name: Dispatch to workflows
        run: |
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" -d '{"event_type": "update_model_list", "client_payload":{"release_version":"${{ github.event.release.tag_name }}"}}' https://api.github.com/repos/${{ matrix.repo }}/dispatches