name: Integration Tests Inference Orchestrator
run-name: Integration tests Inference Orchestrator

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: integration-tests-inference-orchestrator-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  Test-Marqo-Inference-Orchestrator:
    name: Run Marqo Inference Orchestrator Integration Tests
    runs-on: "runs-on=${{ github.run_id }}/family=g4dn.2xlarge/ami=${{ vars.MARQO_CUDA_TESTS_INSTANCE_AMI }}"
    defaults :
      run:
        working-directory: components/inference_orchestrator
    timeout-minutes: 60
    steps:
      - name: Checkout marqo repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          uv sync --dev
          uv run python -c "import nltk; nltk.download('punkt_tab')"

      - name: Spin up the inference environment
        working-directory: ${{ github.workspace }}
        run: |
          docker compose -f compose-model-management.yaml build --quiet
          docker compose -f compose-model-management.yaml --profile gpu up -d --quiet-pull

      - name: Run Integration Tests
        run: |
          uv run pytest tests/integration_tests

#
#      - name: Upload Test Result
#        uses: actions/upload-artifact@v4
#        with:
#          name: marqo-integ-tests-report-${{ env.SHARDS }}shards-${{ env.REPLICAS }}replicas-part${{ matrix.part }}
#          path: |
#            components/marqo/.coverage.${{ matrix.part }}_${{ env.SHARDS }}shards_${{ env.REPLICAS }}replicas
#            components/marqo/pytest_result_summary_${{ env.SHARDS }}shards_${{ env.REPLICAS }}replicas_part${{ matrix.part }}.md
#            components/marqo/pytest_output_${{ env.SHARDS }}shards_${{ env.REPLICAS }}replicas_part${{ matrix.part }}.txt
#          include-hidden-files: true
#
#  Merge-Coverage:
#    name: Merge Coverage And Generate Reports
#    needs:
#      - Test-Marqo
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout marqo repo
#        uses: actions/checkout@v3
#        with:
#          path: marqo/components/marqo
#
#      - name: Download coverage files for this configuration
#        uses: actions/download-artifact@v4
#        with:
#          pattern: marqo-integ-tests-report-${{ env.SHARDS }}shards-${{ env.REPLICAS }}replicas-*
#          path: coverage-${{ env.SHARDS }}shards-${{ env.REPLICAS }}replicas
#
#      - name: Merge Coverage Results
#        run: |
#          cd marqo
#          pip install coverage
#          mkdir -p coverage-reports
#          # Move coverage files to marqo directory for combining
#          find ../coverage-${{ env.SHARDS }}shards-${{ env.REPLICAS }}replicas -name ".coverage.*" -exec cp {} . \;
#          coverage combine
#          # Store the combined coverage in a directory specific to this configuration
#          cp .coverage coverage-reports/.coverage.${{ env.SHARDS }}shards-${{ env.REPLICAS }}replicas
#
#      - name: Upload Merged Coverage Report
#        uses: actions/upload-artifact@v4
#        with:
#          name: marqo-integ-tests-merged-report-${{ env.SHARDS }}shards-${{ env.REPLICAS }}replicas
#          path: marqo/coverage-reports/.coverage.${{ env.SHARDS }}shards-${{ env.REPLICAS }}replicas
#          include-hidden-files: true
