name: Integration Tests Model Management
run-name: Integration tests Model Management

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: integration-tests-model-management-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  Test-Model-Management:
    name: Run Model Management Integration Tests
    runs-on: "runs-on=${{ github.run_id }}/family=g4dn.2xlarge/ami=${{ vars.MARQO_CPU_AMD64_TESTS_INSTANCE_AMI }}"
    defaults:
      run:
        working-directory: components/model_management
    timeout-minutes: 60
    steps:
      - name: Checkout marqo repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Run Triton For integration Tests
        run: |
          cd ../.. # Back to repo root
          mkdir ~/.cache/marqo/models -p # Ensure model cache directory exists for triton to mount
          export MARQO_MODEL_CACHE_PATH=~/.cache/marqo/models
          docker compose -f compose-triton.yaml up -d --quiet-pull

      - name: Run Integration Tests
        run: |
          set -o pipefail
                  
          uv run pytest --durations=100 --cov=src --cov-branch --cov-context=test \
            --md-report --md-report-flavor gfm --md-report-output pytest_result_summary.md \
            tests/integration_tests/ | tee pytest_output.txt

      - name: Upload Test Result
        uses: actions/upload-artifact@v4
        with:
          name: model-management-integ-tests-report
          path: |
            components/model_management/.coverage
            components/model_management/pytest_result_summary.md
            components/model_management/pytest_output.txt
          include-hidden-files: true
