name: Large Scale Performance Tests

on:
  workflow_dispatch:
    inputs:
      test_suite:
        type: choice
        required: true
        options:
          - large_scale_performance_locustfile.py
        description: >
          Location of the Locust file that contains the test suite.

      number_of_users:
        type: string
        required: true
        default: "100"
        description: >
          Total number of simulated users.

      user_spawn_rate:
        type: string
        required: true
        default: "10"
        description: >
          Users spawned per second.

      duration:
        type: string
        required: true
        default: "1h"
        description: >
          Duration of the test (e.g., 1h, 24h, 72h).

      marqo_host:
        type: string
        required: true
        default: "https://your-marqo-instance.com"
        description: >
          Marqo host to run performance test on.

      index_name:
        type: string
        required: true
        default: "locust-test"
        description: >
          Index name to test.

      marqo_cloud_api_key:
        type: string
        required: true
        description: >
          Marqo Cloud API key to use for the test.

jobs:
  Extract-Data:
    name: Extract Required Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          pip install pandas

      - name: Extract Required Data
        run: |
          python perf_tests/extract_required_data.py

      - name: Upload Extracted Data as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: extracted-data
          path: perf_tests/data/extracted_*.csv

  Run-Performance-Test:
    name: Run Large Scale Performance Tests
    needs: Extract-Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Extracted Data
        uses: actions/download-artifact@v3
        with:
          name: extracted-data
          path: perf_tests/data/

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          pip install marqo locust numpy pandas

      - name: Prepare Test Environment
        run: |
          mkdir -p perf_tests/data
          cp perf_tests/large_scale_performance_locustfile.py perf_tests/
          cp perf_tests/bquxjob_5a025798_19241877e37.csv perf_tests/
          # Extracted data is already downloaded to perf_tests/data/
    
      - name: Run Locust Test
        working-directory: perf_tests
        run: |
          locust -f ${{ github.event.inputs.test_suite }} \
            -u ${{ github.event.inputs.number_of_users }} \
            -r ${{ github.event.inputs.user_spawn_rate }} \
            --run-time ${{ github.event.inputs.duration }} \
            --headless \
            --host ${{ github.event.inputs.marqo_host }}
        env:
          MARQO_INDEX_NAME: ${{ github.event.inputs.index_name }}
          MARQO_CLOUD_API_KEY: ${{ github.event.inputs.marqo_cloud_api_key }}

      - name: Upload Telemetry Data
        uses: actions/upload-artifact@v3
        with:
          name: telemetry-data
          path: perf_tests/telemetry_data_*.json

      - name: Upload Telemetry Summaries
        uses: actions/upload-artifact@v3
        with:
          name: telemetry-summaries
          path: perf_tests/telemetry_summary_*.json
