name: Manage EC2 Runner

on:
  workflow_call:
    inputs:
      action:
        description: 'Action to perform on the EC2 runner (start/stop)'
        required: true
        type: string
      base-ami-id:
        description: 'Base AMI ID for the EC2 runner'
        required: false
        type: string
      ec2-instance-type:
        description: 'Instance type for the EC2 runner'
        required: false
        type: string
      label:
        description: 'Label for the EC2 runner'
        required: false
        type: string
      ec2-instance-id:
        description: 'Instance ID for the EC2 runner'
        required: false
        type: string
      instances:
        description: 'Number of instances to start (1-4)'
        required: false
        type: number
        default: 1
    secrets:
      GH_PERSONAL_ACCESS_TOKEN:
        required: true
      MARQO_WORKFLOW_TESTS_SUBNET_ID:
        required: false
      MARQO_WORKFLOW_TESTS_SECURITY_GROUP_ID:
        required: false
    outputs:
      label1:
        description: "EC2 Runner Label 1"
        value: ${{ jobs.Start-Runner.outputs.label1 }}
      label2:
        description: "EC2 Runner Label 2"
        value: ${{ jobs.Start-Runner.outputs.label2 }}
      label3:
        description: "EC2 Runner Label 3"
        value: ${{ jobs.Start-Runner.outputs.label3 }}
      label4:
        description: "EC2 Runner Label 4"
        value: ${{ jobs.Start-Runner.outputs.label4 }}
      ec2-instance-id1:
        description: "EC2 Instance ID 1"
        value: ${{ jobs.Start-Runner.outputs.ec2-instance-id1 }}
      ec2-instance-id2:
        description: "EC2 Instance ID 2"
        value: ${{ jobs.Start-Runner.outputs.ec2-instance-id2 }}
      ec2-instance-id3:
        description: "EC2 Instance ID 3"
        value: ${{ jobs.Start-Runner.outputs.ec2-instance-id3 }}
      ec2-instance-id4:
        description: "EC2 Instance ID 4"
        value: ${{ jobs.Start-Runner.outputs.ec2-instance-id4 }}

jobs:
  Prepare-Matrix:
    runs-on: ubuntu-latest
    outputs:
      instances: ${{ steps.prepare-matrix.outputs.instances }}
    steps:
      - name: Prepare matrix
        id: prepare-matrix
        run: |
          instances=$(seq -s ',' 1 ${{ inputs.instances }} | sed 's/,$//')
          echo "instances=[$instances]" >> $GITHUB_ENV
          echo "instances=[$instances]" >> $GITHUB_OUTPUT
      - name: Show matrix
        run: |
          echo "Generated matrix: ${{ env.instances }}"
  Start-Runner:
    needs:
      Prepare-Matrix
    strategy:
      matrix:
        instance: ${{ fromJSON(needs.Prepare-Matrix.outputs.instances) }}
    if: ${{ inputs.action == 'start' }}
    name: Start EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label1: ${{ steps.set-output.outputs.label1 }}
      label2: ${{ steps.set-output.outputs.label2 }}
      label3: ${{ steps.set-output.outputs.label3 }}
      label4: ${{ steps.set-output.outputs.label4 }}
      ec2-instance-id1: ${{ steps.set-output.outputs.ec2-instance-id1 }}
      ec2-instance-id2: ${{ steps.set-output.outputs.ec2-instance-id2 }}
      ec2-instance-id3: ${{ steps.set-output.outputs.ec2-instance-id3 }}
      ec2-instance-id4: ${{ steps.set-output.outputs.ec2-instance-id4 }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::424082663841:role/GhRunnerManagerRole-Marqo
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ${{ inputs.base-ami-id }}
          ec2-instance-type: ${{ inputs.ec2-instance-type }}
          subnet-id: ${{ secrets.MARQO_WORKFLOW_TESTS_SUBNET_ID }}
          security-group-id: ${{ secrets.MARQO_WORKFLOW_TESTS_SECURITY_GROUP_ID }}
          aws-resource-tags: >
            [
              {"Key": "Name", "Value": "marqo-github-runner-${{ github.run_id }}"},
              {"Key": "GitHubRepo", "Value": "${{ github.repository }}"},
              {"Key": "WorkflowName", "Value": "${{ github.workflow }}"},
              {"Key": "WorkflowRunId", "Value": "${{ github.run_id }}"},
              {"Key": "WorkflowURL", "Value": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"},
              {"Key": "PoloRole", "Value": "testing"}
            ]
      - name: Set output
        id: set-output
        run: |
          echo "label${{ matrix.instance }}=${{ steps.start-ec2-runner.outputs.label }}"
          echo "ec2-instance-id${{ matrix.instance }}=${{ steps.start-ec2-runner.outputs.ec2-instance-id }}"
            

  Stop-Runner:
    name: Stop EC2 runner
    runs-on: ubuntu-latest
    if: ${{ inputs.action == 'stop' }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::424082663841:role/GhRunnerManagerRole-Marqo
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ inputs.label }}
          ec2-instance-id: ${{ inputs.ec2-instance-id }}

permissions:
  contents: read
  id-token: write