# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        cache: "pip"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install marqo
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Get changed files using defaults
      id: changed-files
      uses: tj-actions/changed-files@v29.0.1
      with:
        dir_names: true
      
    - name: List chanegd files with flake8
      run: |
        pip install flake8 
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
          # stop the build if there are Python syntax errors or undefined names
          flake8 $file --count --select=E9,F63,F7,F82 --show-source --statistics --filename *.py
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 $file --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --filename *.py
        done
        
    - name: Test with unittest
      run: python -m unittest tests/processing/test*.py
