name: Run Required Checks
on:
  pull_request:
    branches:
      - mainline
      - releases/*

permissions:
  contents: read
  id-token: write

jobs:
  Determine-changes:
    name: Determine Scope of Changes
    runs-on: ubuntu-latest
    outputs:
      non_documentation_changes_found: ${{ steps.check_changes.outputs.non_documentation_changes_found }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for Non-Markdown Changes
        id: check_changes
        run: |
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"
          
          if [ -z "$BEFORE" ] || \
             git diff --name-only "$BEFORE" "$AFTER" | grep -qvE '\.md$'
          then
            # either BEFORE was empty, or we found at least one non‑.md change
            echo "non_documentation_changes_found=true" >> "$GITHUB_OUTPUT"
          else
            # BEFORE was set and all changed files end in .md
            echo "non_documentation_changes_found=false" >> "$GITHUB_OUTPUT"
          fi

  Run-integration-tests:
    needs: Determine-changes
    if: ${{ needs.Determine-changes.outputs.non_documentation_changes_found == 'true' }}
    uses: ./.github/workflows/integration_tests_CI.yml
    with:
      number_of_shards: 1
      number_of_replicas: 0
    secrets: inherit

  # TODO: Add more jobs here as needed
