name: Run Required Checks
on:
  pull_request:
    branches:
      - mainline
      - releases/*
  push:
    branches:
      - mainline
      - releases/*

permissions:
  contents: read
  id-token: write

jobs:
  Determine-changes:
    name: Determine Scope of Changes
    runs-on: ubuntu-latest
    outputs:
      non_documentation_changes_found: ${{ steps.check_changes.outputs.non_documentation_changes_found }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: marqo

      - name: Check for Non-Markdown Changes
        id: check_changes
        run: |
          cd marqo
          set -x
          
          # Determine BASE_COMMIT and HEAD_COMMIT based on the event type
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            BASE_COMMIT=${{ github.event.pull_request.base.sha }}
            HEAD_COMMIT=${{ github.event.pull_request.head.sha }}
          elif [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            BASE_COMMIT=${{ github.event.before }}
            HEAD_COMMIT=${{ github.sha }}
          elif [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            # For manual dispatch, we always run the tests
            echo "non_documentation_changes_found=true" >> "$GITHUB_OUTPUT"
            exit 0
          else
            echo "Unsupported event: ${GITHUB_EVENT_NAME}"
            exit 1
          fi

          # Debug: Print base and head commits
          echo "Base commit: $BASE_COMMIT"
          echo "Head commit: $HEAD_COMMIT"

          # Perform the diff to check for non-documentation changes
          if git diff --name-only $BASE_COMMIT $HEAD_COMMIT -- | grep -vE '\.(md)$'; then
            echo "non_documentation_changes_found=true" >> "$GITHUB_OUTPUT"
          else
            echo "non_documentation_changes_found=false" >> "$GITHUB_OUTPUT"
          fi

  Run-integration-tests:
    needs: Determine-changes
    if: ${{ needs.Determine-changes.outputs.non_documentation_changes_found == 'true' }}
    uses: ./.github/workflows/integration_tests_CI.yml
    with:
      number_of_shards: 1
      number_of_replicas: 0
    secrets: inherit

  Run-largemodel-integration-tests:
    needs: Determine-changes
    if: ${{ needs.Determine-changes.outputs.non_documentation_changes_found == 'true' }}
    uses: ./.github/workflows/largemodel_integration_tests_CI.yml
    secrets: inherit

  Run-unit-tests:
    needs: Determine-changes
    if: ${{ needs.Determine-changes.outputs.non_documentation_changes_found == 'true' }}
    uses: ./.github/workflows/unit_tests.yml
    secrets: inherit

  Combine-Coverage-Reports:
    needs:
      - Run-integration-tests
      - Run-largemodel-integration-tests
      - Run-unit-tests
    if: ${{ always() && needs.Determine-changes.outputs.non_documentation_changes_found == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout marqo repo
        uses: actions/checkout@v3
        with:
          path: marqo

      - name: Download integration tests coverage
        uses: actions/download-artifact@v4
        with:
          name: marqo-integ-tests-report
          path: integration-tests-coverage
          
      - name: Download large model tests coverage
        uses: actions/download-artifact@v4
        with:
          name: marqo-largemodel-tests-report
          path: largemodel-tests-coverage
          
      - name: Download unit tests coverage
        uses: actions/download-artifact@v4
        with:
          name: marqo-unit-tests-report
          path: unit-tests-coverage
          
      - name: List downloaded artifacts
        run: |
          echo "Listing all downloaded artifacts:"
          echo "Integration tests coverage:"
          ls -la integration-tests-coverage/
          echo "Large model tests coverage:"
          ls -la largemodel-tests-coverage/
          echo "Unit tests coverage:"
          ls -la unit-tests-coverage/
          
      - name: Install coverage package
        run: |
          pip install coverage
          pip install diff-cover

      - name: Move coverage files
        run: |
          # Create a directory to store all coverage data
          mkdir -p coverage_data
          mkdir -p unit_coverage_data
          mkdir -p integ_coverage_data
          
          # Move all coverage files to a single directory
          cp integration-tests-coverage/.coverage coverage_data/integration.coverage || true
          cp largemodel-tests-coverage/.coverage coverage_data/largemodel.coverage || true
          cp unit-tests-coverage/.coverage coverage_data/unit.coverage || true
          
          # Copy to separate directories for individual analysis
          cp integration-tests-coverage/.coverage integ_coverage_data/integration.coverage || true
          cp largemodel-tests-coverage/.coverage integ_coverage_data/largemodel.coverage || true
          cp unit-tests-coverage/.coverage unit_coverage_data/unit.coverage || true
          
          # Create combined reports directory
#          mkdir -p combined-reports

          # Store individual HTML reports
#          mkdir -p combined-reports/integration
#          mkdir -p combined-reports/largemodel
#          mkdir -p combined-reports/unit
#          mkdir -p combined-reports/combined
          
          # Copy HTML reports
#          [ -d "integration-tests-coverage/htmlcov" ] && cp -r integration-tests-coverage/htmlcov/* combined-reports/integration/ || true
#          [ -d "largemodel-tests-coverage/htmlcov" ] && cp -r largemodel-tests-coverage/htmlcov/* combined-reports/largemodel/ || true
#          [ -d "unit-tests-coverage/htmlcov" ] && cp -r unit-tests-coverage/htmlcov/* combined-reports/unit/ || true

          export PYTHONPATH="../marqo"

          # Combine coverage data if available
          cd coverage_data
          ls -la
          echo "Combining coverage files..."
          coverage combine integration.coverage largemodel.coverage unit.coverage
          coverage xml -o coverage.xml
          coverage html --directory=htmlcov
          
          # Generate unit test coverage data
          cd ../unit_coverage_data
          coverage combine unit.coverage
          coverage xml -o coverage.xml
          coverage html --directory=htmlcov
          
          # Generate integration test coverage data (including largemodel)
          cd ../integ_coverage_data
          coverage combine integration.coverage largemodel.coverage
          coverage xml -o coverage.xml
          coverage html --directory=htmlcov

      - name: Install diff-cover
        run: |
          pip install diff-cover

      - name: Check diff unit test coverage (95% threshold)
        id: unit_diff_coverage
        if: github.event_name == 'pull_request'
        continue-on-error: true
        run: |
          cd unit_coverage_data
          
          EXPORT PYTHONPATH="../marqo"
          
          export BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          echo "Running diff-cover against branch $BASE_BRANCH"
          git fetch origin $BASE_BRANCH:$BASE_BRANCH
          diff-cover coverage.xml --html-report diff_cov.html --markdown-report diff_cov.md \
            --compare-branch $BASE_BRANCH --fail-under=95

      - name: Check diff integ test coverage (80% threshold)
        id: integ_diff_coverage
        if: github.event_name == 'pull_request'
        continue-on-error: true
        run: |
          cd integ_coverage_data
          
          EXPORT PYTHONPATH="../marqo"
          
          export BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          echo "Running diff-cover against branch $BASE_BRANCH"
          git fetch origin $BASE_BRANCH:$BASE_BRANCH
          diff-cover coverage.xml --html-report diff_cov.html --markdown-report diff_cov.md \
            --compare-branch $BASE_BRANCH --fail-under=80

      - name: Check diff combined test coverage (90% threshold)
        id: integ_diff_coverage
        if: github.event_name == 'pull_request'
        continue-on-error: true
        run: |
          cd coverage_data
          
          EXPORT PYTHONPATH="../marqo"
          
          export BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          echo "Running diff-cover against branch $BASE_BRANCH"
          git fetch origin $BASE_BRANCH:$BASE_BRANCH
          diff-cover coverage.xml --html-report diff_cov.html --markdown-report diff_cov.md \
            --compare-branch $BASE_BRANCH --fail-under=90

      - name: Upload combined coverage report
        uses: actions/upload-artifact@v4
        with:
          name: combined-test-coverage
          path: |
            coverage_data/coverage.xml
            coverage_data/htmlcov/
#            diff_cov.html
            
#      - name: Coverage Report Summary
#        if: always() && github.event_name == 'pull_request'
#        run: |
#          if [ -f "combined-reports/coverage_summary.md" ]; then
#            cat combined-reports/coverage_summary.md >> $GITHUB_STEP_SUMMARY
#          else
#            echo "No coverage summary available" >> $GITHUB_STEP_SUMMARY
#          fi
          
      - name: Fail if coverage thresholds not met
        if: github.event_name == 'pull_request' && (steps.overall_coverage.outputs.status == 'failure' || steps.diff_coverage.outputs.status == 'failure' || steps.unit_coverage.outputs.status == 'failure' || steps.integ_coverage.outputs.status == 'failure' || steps.unit_diff_coverage.outputs.status == 'failure' || steps.integ_diff_coverage.outputs.status == 'failure')
        run: |
          echo "Coverage threshold check failed"
          if [ "${{ steps.unit_coverage.outputs.status }}" == "failure" ]; then
            echo "❌ Unit test coverage: ${{ steps.unit_coverage.outputs.percentage }}% (required: 20%)"
          fi
          if [ "${{ steps.integ_coverage.outputs.status }}" == "failure" ]; then
            echo "❌ Integration test coverage: ${{ steps.integ_coverage.outputs.percentage }}% (required: 70%)"
          fi
          if [ "${{ steps.overall_coverage.outputs.status }}" == "failure" ]; then
            echo "❌ Overall coverage: ${{ steps.overall_coverage.outputs.percentage }}% (required: 70%)"
          fi
          if [ "${{ steps.unit_diff_coverage.outputs.status }}" == "failure" ]; then
            echo "❌ Unit test diff coverage: ${{ steps.unit_diff_coverage.outputs.percentage }}% (required: 90%)"
          fi
          if [ "${{ steps.integ_diff_coverage.outputs.status }}" == "failure" ]; then
            echo "❌ Integration test diff coverage: ${{ steps.integ_diff_coverage.outputs.percentage }}% (required: 80%)"
          fi
          if [ "${{ steps.diff_coverage.outputs.status }}" == "failure" ]; then
            echo "❌ Combined diff coverage: ${{ steps.diff_coverage.outputs.percentage }}% (required: 90%)"
          fi
          exit 1

  # GitHub status will rely on the result of this step to determine if the PR is ready for merge
  Report-required-test-status:
    needs: [ Determine-changes, Run-integration-tests ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Set integration test status
        run: |
          if [[ "${{ needs.Determine-changes.outputs.non_documentation_changes_found }}" == "false" ]]; then
            echo "Integration tests skipped due to markdown-only changes."
          elif [[ "${{ needs.Run-integration-tests.result }}" == "success" ]]; then
            echo "Integration tests completed successfully."
          else
            echo "Integration tests failed or did not run."
            exit 1
          fi