name: test_documentation

on:
  push:
    branches:
      - mainline
      - releases/*

permissions:
  contents: read

jobs:
  Test-Documentation:
    name: Run Documentation Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout marqo repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: marqo

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r marqo/requirements.dev.txt
          pip install pytest==7.4.0

      - name: Run Documentation Tests
        run: |
          export PYTHONPATH="./marqo/tests:./marqo/src:./marqo"
          pytest marqo/tests/test_documentation.py
