name: Run unit tests

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - mainline
      - releases/*
  pull_request:
    branches:
      - mainline
      - releases/*

jobs:
  run-unit-tests:
    name: Run Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install tox
        run: pip install tox==3.26

      - name: Run UnitTests
        run: tox -e unit-tests