name: unit_test_200gb_CI
run-name: Unit Tests with ${{ inputs.number_of_shards }} shards and ${{ inputs.number_of_replicas }} replicas
# runs unit tests on AMD64 machine

on:
  workflow_call:
    inputs:
      number_of_shards:
        type: number
        description: 'Number of shards (content nodes per group in Vespa). Minimum of 1.'
        required: true
        default: 1

      number_of_replicas:
        type: number
        description: 'Number of replicas (groups in Vespa minus 1). Minimum of 0.'
        required: true
        default: 0

  workflow_dispatch:
    inputs:
      number_of_shards:
        type: number
        description: 'Number of shards (content nodes per group in Vespa). Minimum of 1.'
        required: true
        default: 1

      number_of_replicas:
        type: number
        description: 'Number of replicas (groups in Vespa - 1)'
        required: true
        default: 0

  push:
    branches:
      - mainline
      - releases/*
  pull_request:
    branches:
      - mainline
      - releases/*

concurrency:
  group: unit-tests-${{ github.ref }}-${{ inputs.number_of_shards }}-${{ inputs.number_of_replicas }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Start-Runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MARQO_WORKFLOW_TESTS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MARQO_WORKFLOW_TESTS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ${{ vars.MARQO_CPU_AMD64_TESTS_INSTANCE_AMI }}
          ec2-instance-type: m6i.xlarge
          subnet-id: ${{ secrets.MARQO_WORKFLOW_TESTS_SUBNET_ID }}
          security-group-id: ${{ secrets.MARQO_WORKFLOW_TESTS_SECURITY_GROUP_ID }}
          aws-resource-tags: > # optional, requires additional permissions
            [
              {"Key": "Name", "Value": "marqo-github-runner-${{ github.run_id }}"},
              {"Key": "GitHubRepo", "Value": "${{ github.repository }}"},
              {"Key": "WorkflowName", "Value": "${{ github.workflow }}"},
              {"Key": "WorkflowRunId", "Value": "${{ github.run_id }}"},
              {"Key": "WorlflowURL", "Value": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"},
              {"Key": "PoloRole", "Value": "testing"}
            ]

  Determine-Vespa-Setup:
    runs-on: ubuntu-latest
    outputs:
      VESPA_MULTINODE_SETUP: ${{ steps.set_var.outputs.VESPA_MULTINODE_SETUP }}
      IGNORED_TESTS: ${{ steps.set_var.outputs.IGNORED_TESTS }}
    steps:
      - name: Determine VESPA_MULTINODE_SETUP
        id: set_var
        run: |
          # Initialize as false
          echo "VESPA_MULTINODE_SETUP=false" >> $GITHUB_OUTPUT
          echo "IGNORED_TESTS=" >> $GITHUB_OUTPUT
          
          # Check if the event is workflow_call or workflow_dispatch
          if [[ "${{ github.event_name }}" == "workflow_call" || "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # Extract inputs safely, defaulting to 1 (for shards), 0 (for replicas) if not present
            NUMBER_OF_SHARDS="${{ inputs.number_of_shards || 1 }}"
            NUMBER_OF_REPLICAS="${{ inputs.number_of_replicas || 0 }}"
          
            # Convert inputs to integers
            NUMBER_OF_SHARDS_INT=$(echo "$NUMBER_OF_SHARDS" | awk '{print int($0)}')
            NUMBER_OF_REPLICAS_INT=$(echo "$NUMBER_OF_REPLICAS" | awk '{print int($0)}')
          
            # Evaluate the conditions
            if [[ "$NUMBER_OF_SHARDS_INT" -gt 1 || "$NUMBER_OF_REPLICAS_INT" -gt 0 ]]; then
              echo "Using multi-node Vespa setup. Shards are $NUMBER_OF_SHARDS_INT and replicas are $NUMBER_OF_REPLICAS_INT."
              echo "VESPA_MULTINODE_SETUP=true" >> $GITHUB_OUTPUT
              # If multinode vespa, ignore unrelated tests to save time
              echo "IGNORED_TESTS=--ignore=tests/core/inference --ignore=tests/processing --ignore=tests/s2_inference" >> $GITHUB_OUTPUT
            fi
          fi

  Test-Marqo:
    name: Run Unit Tests
    needs:
      - Start-Runner
      - Determine-Vespa-Setup
    runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner
    environment: marqo-test-suite
    env:
      VESPA_MULTINODE_SETUP: ${{ needs.Determine-Vespa-Setup.outputs.VESPA_MULTINODE_SETUP }}
      IGNORED_TESTS: ${{ needs.Determine-Vespa-Setup.outputs.IGNORED_TESTS }}
    steps:
      - name: Checkout marqo repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: marqo

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Checkout marqo-base for requirements
        uses: actions/checkout@v3
        with:
          repository: marqo-ai/marqo-base
          path: marqo-base

      - name: Install dependencies
        run: |
          pip install -r marqo-base/requirements/amd64-gpu-requirements.txt
          # override base requirements with marqo requirements, if needed:
          pip install -r marqo/requirements.dev.txt

      - name: Download nltk data
        run: |
            python -m nltk.downloader punkt_tab

      - name: Build Vespa
        run: |
          systemctl stop unattended-upgrades
          apt-get remove -y unattended-upgrades

          # Function to wait for the dpkg lock to be released
          function wait_for_dpkg_lock() {
            while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
              echo "Waiting for the dpkg lock to be released..."
              sleep 5
            done
          }

          # Wait for the dpkg lock before updating and installing
          wait_for_dpkg_lock

          echo "Updating package list"
          apt-get update -y

          # Build Vespa components
          echo "Installing jdk 17"
          sudo apt-get install openjdk-17-jdk -y
          echo "Installing maven"
          sudo apt-get install maven -y
          echo "Building Vespa components"
          cd marqo/vespa
          mvn clean package

      - name: Start Vespa
        run: |
          # Define these for checking if Vespa is ready
          export VESPA_CONFIG_URL=http://localhost:19071
          export VESPA_DOCUMENT_URL=http://localhost:8080
          export VESPA_QUERY_URL=http://localhost:8080
          
          cd marqo/scripts/vespa_local
          set -x
          START_SCRIPT_OUTPUT=$(python vespa_local.py start --Shards ${{ inputs.number_of_shards || 1 }} --Replicas ${{ inputs.number_of_replicas || 0 }})
          set +x

          echo "Waiting for Vespa to start"
          for i in {1..20}; do
              echo -ne "Waiting... $i seconds\r"
              sleep 1
          done
          echo -e "\nDone waiting."

          # Zip up schemas, hosts, and services
          sudo apt-get install zip -y
          zip -r vespa_tester_app.zip . -x README.md .env .gitignore "*.yml"  # zip the whole directory except for the listed files

          # Deploy application with test schema
          curl --header "Content-Type:application/zip" --data-binary @vespa_tester_app.zip http://localhost:19071/application/v2/tenant/default/prepareandactivate
    
          # For single node: wait for vespa to start (document url):
          if [[ "$VESPA_MULTINODE_SETUP" == "false" ]]; then
            timeout 10m bash -c 'until curl -f -X GET $VESPA_DOCUMENT_URL >/dev/null 2>&1; do echo "  Waiting for Vespa document API to be available..."; sleep 10; done;' || \
              (echo "Vespa (Document URL) did not start in time" && exit 1)
            echo "Vespa document API is available. Local single node Vespa setup complete."
            
          elif [[ "$VESPA_MULTINODE_SETUP" == "true" ]]; then
            # For multinode: wait for all vespa nodes to start
            echo "Extracting URLs from vespa_local.py output..."
            URL_LIST=$(echo "$START_SCRIPT_OUTPUT" | grep -Eo 'http://[^ ]+')
      
            if [[ -z "$URL_LIST" ]]; then
                echo "Error: No URLs found in vespa_local.py output."
                exit 1
            fi
      
            echo "Found the following URLs to check:"
            echo "$URL_LIST"
      
            # Total timeout in seconds (10 minutes)
            TOTAL_TIMEOUT=600
            INTERVAL=10
            MAX_ATTEMPTS=$((TOTAL_TIMEOUT / INTERVAL))
          
            for url in $URL_LIST; do
                CURRENT_ATTEMPT=0
                echo "Checking health of: $url"
                while ! curl -f -s $url >/dev/null 2>&1; do
                    if [[ $CURRENT_ATTEMPT -ge $MAX_ATTEMPTS ]]; then
                        echo "Error: Timeout reached. Exiting."
                        exit 1
                    fi
                    echo "$url is not yet ready. Waiting for $INTERVAL seconds..."
                    sleep $INTERVAL
                    CURRENT_ATTEMPT=$((CURRENT_ATTEMPT + 1))
                done
                echo "$url is ready."
            done
            echo "All API and content nodes are available. Local multinode Vespa setup complete."
          fi

          # Delete the zip file
          rm vespa_tester_app.zip
          echo "Deleted vespa_tester_app.zip"

      - name: Run Unit Tests
        run: |
          # Define these for use by marqo
          export VESPA_CONFIG_URL=http://localhost:19071
          export VESPA_DOCUMENT_URL=http://localhost:8080
          export VESPA_QUERY_URL=http://localhost:8080

          export PRIVATE_MODEL_TESTS_AWS_ACCESS_KEY_ID=${{ secrets.PRIVATE_MODEL_TESTS_AWS_ACCESS_KEY_ID }}
          export PRIVATE_MODEL_TESTS_AWS_SECRET_ACCESS_KEY=${{ secrets.PRIVATE_MODEL_TESTS_AWS_SECRET_ACCESS_KEY }}
          export PRIVATE_MODEL_TESTS_HF_TOKEN=${{ secrets.PRIVATE_MODEL_TESTS_HF_TOKEN }}

          cd marqo
          export PYTHONPATH="./tests:./src:."
          pytest ${{ env.IGNORED_TESTS }} --ignore=tests/core/index_management/test_index_management.py --ignore=tests/core/monitoring/test_monitoring.py --ignore=tests/test_documentation.py --ignore=tests/backwards_compatibility_tests --durations=100 --cov=src --cov-branch --cov-context=test --cov-report=html:cov_html --cov-report=lcov:lcov.info tests

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: marqo-test-report
          path: marqo/cov_html/

  Stop-Runner:
    name: Stop self-hosted EC2 runner
    needs:
      - Start-Runner # required to get output from the start-runner job
      - Test-Marqo # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MARQO_WORKFLOW_TESTS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MARQO_WORKFLOW_TESTS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
