name: Run unit tests
# runs unit tests on standard machine

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - mainline
      - releases/*
  pull_request:
    branches:
      - mainline
      - releases/*

concurrency:
  group: unit-tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Test-Marqo:
    name: Run unit tests
    runs-on: ubuntu-latest
    environment: marqo-test-suite
    steps:
      - name: Check out marqo repo
        uses: actions/checkout@v3
        with:
          path: marqo
          fetch-depth: 0  # Needed for diff coverage

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Checkout marqo-base for requirements
        uses: actions/checkout@v3
        with:
          repository: marqo-ai/marqo-base
          path: marqo-base

      - name: Install dependencies
        run: |
          pip install -r marqo-base/requirements/amd64-gpu-requirements.txt
          # override base requirements with marqo requirements, if needed:
          pip install -r marqo/requirements.dev.txt

      - name: Run unit tests
        id: run_unit_tests
        continue-on-error: true
        run: |
          cd marqo
          export PYTHONPATH="./src"
          pytest --durations=100 --cov=src --cov-branch --cov-context=test \
            --cov-report=html:cov_html --cov-report=xml:cov.xml --cov-report term:skip-covered \
            --md-report --md-report-flavor gfm --md-report-output pytest_result_summary.md \
            tests/unit_tests/ | tee pytest_output.txt

      - name: Check new code coverage
        id: check_test_coverage
        if: github.event_name == 'pull_request'
        run: |
          cd marqo
          diff-cover cov.xml --compare-branch=origin/${{ github.base_ref }} --fail-under=95 \
            --html-report diff_cov.html --markdown-report diff_cov.md

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: marqo-test-report
          path: |
            marqo/cov_html/
            marqo/diff_cov.html

      - name: Test and coverage report summary
        run: |
          echo "# Test Summary" >> $GITHUB_STEP_SUMMARY
          cat marqo/pytest_result_summary.md >> $GITHUB_STEP_SUMMARY
          
          echo "# Coverage summary, slow tests and failed tests" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          awk '/---------- coverage:/ {flag=1} flag' marqo/pytest_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          
          cat marqo/diff_cov.md >> $GITHUB_STEP_SUMMARY

      - name: Fail if tests or coverage failed
        if: ${{ steps.run_unit_tests.outcome == 'failure' || steps.check_test_coverage.outcome == 'failure' }}
        run: |
          echo "Tests or coverage checks failed. Marking job as failed."
          exit 1
        shell: bash