name: Run unit tests
# runs unit tests on standard machine

on:
  workflow_call:
  workflow_dispatch:

# concurrency:
#   group: unit-tests-${{ github.ref }}
#   cancel-in-progress: true

permissions:
  contents: read

jobs:
  Test-Marqo:
    name: Run unit tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out marqo repo
        uses: actions/checkout@v3
        with:
          path: marqo

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Checkout marqo-base for requirements
        uses: actions/checkout@v3
        with:
          repository: marqo-ai/marqo-base
          path: marqo-base

      - name: Install dependencies
        run: |
          pip install -r marqo-base/requirements/amd64-gpu-requirements.txt
          # override base requirements with marqo requirements, if needed:
          pip install -r marqo/requirements.txt
          pip install -r marqo/requirements.dev.txt
          python -m nltk.downloader punkt_tab

      - name: Run unit tests
        id: run_unit_tests
        run: |
          cd marqo
          export PYTHONPATH="./src:."
          set -o pipefail
          pytest --durations=100 --cov=src --cov-branch --cov-context=test \
            --md-report --md-report-flavor gfm --md-report-output pytest_result_summary.md \
            tests/unit_tests/ | tee pytest_output.txt

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: marqo-unit-tests-report
          path: |
            marqo/.coverage
          include-hidden-files: true

      - name: Test and coverage report summary
        run: |
          echo "# Test Summary" >> $GITHUB_STEP_SUMMARY
          cat marqo/pytest_result_summary.md >> $GITHUB_STEP_SUMMARY
          
          echo "# Coverage summary, slow tests and failed tests" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          awk '/---------- coverage:/ {flag=1} flag' marqo/pytest_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
